package io.github.bamos

object Whitelist {
  val users = Seq(
    "adius",
    "adobe-research",
    "ajn123",
    "bamos",
    "bryangarza",
    "cmusatyalab",
    "darksigma",
    "docker",
    "jebes",
    "HackathonHackers",
    "hamiltont",
    "ObeliskIsHuge",
    "rhema",
    "snowplow",
    "tejasmanohar",
    "themattman",
    "VT-Magnum-Research",
    "WalnutiQ",
    "zmughal",
    "geotrellis",
    "twitter",
    "github",
    "facebook",
    "etsy",
    "square",
    "amplab",
    "fnothaft",
    "bigdatagenomics",
    "homebrew",
    "puppetlabs",
    "rails",
    "google",
    "okfn",
    "humblesoftware",
    "ecomfe",
    "mozilla",
    "spine",
    "jez",
    "haskell",
    "coreos",
    "scotty-web"
  ).map(_.toLowerCase)
}
